### Register a new user
POST http://localhost:5000/Users
Content-Type: application/json

{
    "name_user": "José",
    "lastName_user": "Santana",
    "email_user": "josesantana05@gmail.com",
    "password_user": "JSa06..."
}

### Login a user
POST http://localhost:5000/Users/login
Content-Type: application/json

{
    "email_user": "joseasantana05@gmail.com",
    "password_user": "JSa06..."
}

### Close a user session
POST http://localhost:5000/Users/logout
Content-Type: application/json

{
    "email_user": "joseasantana05@gmail.com"
}

### Update a user
PATCH http://localhost:5000/Users/update/1
Content-Type: application/json

{
    "account_balance_user": 1000.00,
    "meta_user": 3500.00
}

### Get the all finances 
GET http://localhost:5000/Finances

### Get finance by ID
GET http://localhost:5000/Finances/1

### Get the all finances of a user
GET http://localhost:5000/Finances/user/1

### Get a specific finance for amount
GET http://localhost:5000/Finances/amount/1600.00

### Get a sepecific finance for type
GET http://localhost:5000/Finances/type/Ingreso

### Get a specific finance for category
GET http://localhost:5000/Finances/category/Servicios

### Get a specific finance for date
GET http://localhost:5000/Finances/date/2025-07-01/8

### Create a new finance record
POST http://localhost:5000/Finances/create/3
Content-Type: application/json

{
    "description_finance": "Salario mensual de la empresa",
    "amount_finance": 1500.00,
    "date_finance": "2023-10-01",
    "type_finance": "Ingreso",
    "category_finance": "Servicios"
}

### Delete a finance record
DELETE http://localhost:5000/Finances/delete/11


### Update a finance record
PATCH http://localhost:5000/Finances/update/5
Content-Type: application/json

{
    "name_finance": "Salario de la empresa actualizado",
    "description_finance": "Salario mensual de la empresa actualizado",
    "amount_finance": 1600.00,
    "date_finance": "2023-10-01",
    "type_finance": "Ingreso",
    "category_finance": "Servicios"
}
